ALTER TABLE projects ADD COLUMN category_id TEXT;
ALTER TABLE projects ADD COLUMN assignee_type TEXT NOT NULL DEFAULT 'UNASSIGNED';
ALTER TABLE projects ADD COLUMN is_private BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN simplified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN style TEXT NOT NULL DEFAULT 'classic';
ALTER TABLE projects ADD COLUMN url TEXT NOT NULL DEFAULT '';
