replicaCount: 1
image:
  api: ghcr.io/it4nodummies/heureum-api:latest
  worker: ghcr.io/it4nodummies/heureum-worker:latest
  frontend: ghcr.io/it4nodummies/heureum-frontend:latest
config:
  appSecret: ""
  dbDriver: postgres
  dbDsn: "postgres://heureum:heureum@postgres:5432/heureum?sslmode=disable"
  redisUrl: "redis://redis:6379/0"
  baseUrl: "http://localhost"
  smtpHost: ""
ingress:
  enabled: false
  host: jira.example.com
postgresql:
  enabled: false
redis:
  enabled: false
