apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-jira.fullname" . }}-secret
  labels:
    {{- include "open-jira.labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.config.appSecret | b64enc | quote }}
