apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heureum.fullname" . }}-secret
  labels:
    {{- include "heureum.labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.config.appSecret | b64enc | quote }}
